### PR TITLE
Add asdf installation option

### PR DESCRIPTION
**Pull request by cmaher**

### CODE REVIEW

**Comment by kyoh86** [comment]
I won't manage it.

**Comment by cmaher** [comment]
Unless you change the way you name your releases, there's nothing to manage. The plugin is already in the asdf repository.

Plugin list: https://github.com/asdf-vm/asdf-plugins
Plugin: https://github.com/paxosglobal/asdf-richgo

**Comment by kyoh86** [comment]
hm... ok

**Comment by cmaher** [comment]
sorry for not being clearer in the initial message

**Pull request merged**
